/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { MusicViddle } from "./MusicViddle";
export type { Ownable } from "./Ownable";
export type { ViddleCoin } from "./ViddleCoin";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { MusicViddle__factory } from "./factories/MusicViddle__factory";
export { Ownable__factory } from "./factories/Ownable__factory";
export { ViddleCoin__factory } from "./factories/ViddleCoin__factory";
